### ISSUE TITLE
Breaks windows audio service/ beat saber

### ISSUE THREAD

**Issue by soitsdragon** [Zingabopp/OBSControl#29]
I updated to 2.0.2-Beta and now it crashes my game for deleting files also my windows audio service stops running resulting in no audio.

**Comment by Zingabopp** [comment]
You'll have to be more specific on what exactly you're doing (and include logs). The only time OBSControl touches the file system is to check if your recording directory exists and to rename a recording right after it's stopped, so I'm not sure how deleting a file would crash the game. As for the audio service, auto control can be disabled in the options.

**Comment by soitsdragon** [comment]
[_latest.log](https://github.com/Zingabopp/OBSControl/files/6260283/_latest.log)
This is the latest log. And what I mean is when I try and launch beat saber it crashes then steam tells me 10 files are missing., When I fix that I try and launch the game again only to be crashed again. This all stopped after I uninstalled the mod. Also when I press launch my windows audio service stops working,

**Comment by Zingabopp** [comment]
Ah I see, It's doing that because of the way the audio service portion of OBSControl stores your devices using shortened names. You have two named `Headphones`. A quick fix would be to rename `Headphones (Oculus Virtual Audio Device)` to something like `Oculus Headphones` in the Windows sound settings for now. This will be fixed in a future version.

**Comment by Gordin** [comment]
Hm, this is weird, I remember specifically that I changed this to use the part inside the `( )` for the short name and not the string before it, because I have multiple devices that start with `Speakers`, you can even see it in the log.
```
[DEBUG @ 14:31:25 | OBSControl] |ADC| Adding "Oculus Virtual Audio" -> "Headphones (Oculus Virtual Audio Device)"
[DEBUG @ 14:31:25 | OBSControl] |ADC| Adding "Headphones (Oculus Virtual Audio Device)" -> "Oculus Virtual Audio"
.....
[DEBUG @ 14:31:25 | OBSControl] |ADC| Adding "Headphones (Oculus Virtual Audio Device)" -> "Headphones"
```
But it seems like it's adding the device twice, and then it chooses the other part, but the second one shouldn't be there in the first place 0.o I guess I'll look into that some time this week when I have time.

**Comment by Gordin** [comment]
(Also, if there is a duplicate key it should fall back to not use shortened names at all, but looks like I didn't catch the correct Exception for that...)

**Comment by soitsdragon** [comment]
> Ah I see, It's doing that because of the way the audio service portion of OBSControl stores your devices using shortened names. You have two named `Headphones`. A quick fix would be to rename `Headphones (Oculus Virtual Audio Device)` to something like `Oculus Headphones` in the Windows sound settings for now. This will be fixed in a future version.

I cant rename this device since that is the name of the audio driver.
![Screenshot_1](https://user-images.githubusercontent.com/30652248/113629606-45e07f00-962c-11eb-93cf-62eec8727cfe.png)

**Comment by Gordin** [comment]
@DragonPlays in that window, you can replace the `Headphones` in the box at the top with something different, that should rename the device to `SOMETHING ELSE (Oculus Virtual Audio Device)`
